# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmModelSetup.ui'
#
# Created: Fri Jul 13 11:52:13 2012
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_JanelaModelo(object):
    def setupUi(self, JanelaModelo):
        JanelaModelo.setObjectName("JanelaModelo")
        JanelaModelo.resize(652, 480)
        JanelaModelo.setModal(True)
        self.groupBox_4 = QtGui.QGroupBox(JanelaModelo)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 30, 281, 61))
        self.groupBox_4.setObjectName("groupBox_4")
        self.cbModelList = QtGui.QComboBox(self.groupBox_4)
        self.cbModelList.setGeometry(QtCore.QRect(20, 30, 241, 21))
        self.cbModelList.setObjectName("cbModelList")
        self.cbModelList.addItem(QtCore.QString())
        self.cbModelList.addItem(QtCore.QString())
        self.cbModelList.addItem(QtCore.QString())
        self.cbModelList.addItem(QtCore.QString())
        self.fmExpContDet = QtGui.QFrame(JanelaModelo)
        self.fmExpContDet.setGeometry(QtCore.QRect(340, 20, 291, 411))
        self.fmExpContDet.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fmExpContDet.setFrameShadow(QtGui.QFrame.Raised)
        self.fmExpContDet.setObjectName("fmExpContDet")
        self.groupBox_3 = QtGui.QGroupBox(self.fmExpContDet)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 30, 271, 341))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(40, 30, 224, 271))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_9 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_4 = QtGui.QLabel(self.layoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_10.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEditPopExp = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEditPopExp.setObjectName("lineEditPopExp")
        self.gridLayout_10.addWidget(self.lineEditPopExp, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_5 = QtGui.QLabel(self.layoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_11.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEditTempoExp = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEditTempoExp.setObjectName("lineEditTempoExp")
        self.gridLayout_11.addWidget(self.lineEditTempoExp, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_11, 2, 0, 1, 1)
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBox_5 = QtGui.QGroupBox(self.layoutWidget_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_13.addLayout(self.gridLayout_14, 1, 0, 1, 1)
        self.lineEditNatalidade = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditNatalidade.setObjectName("lineEditNatalidade")
        self.gridLayout_13.addWidget(self.lineEditNatalidade, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.layoutWidget_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_15.addLayout(self.gridLayout_16, 1, 0, 1, 1)
        self.lineEditMortalidade = QtGui.QLineEdit(self.groupBox_6)
        self.lineEditMortalidade.setObjectName("lineEditMortalidade")
        self.gridLayout_15.addWidget(self.lineEditMortalidade, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_12, 3, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem2, 1, 0, 1, 1)
        self.pbOk = QtGui.QPushButton(JanelaModelo)
        self.pbOk.setGeometry(QtCore.QRect(390, 440, 75, 23))
        self.pbOk.setObjectName("pbOk")
        self.pbCancel = QtGui.QPushButton(JanelaModelo)
        self.pbCancel.setGeometry(QtCore.QRect(480, 440, 75, 23))
        self.pbCancel.setObjectName("pbCancel")
        self.fmLogistico = QtGui.QFrame(JanelaModelo)
        self.fmLogistico.setGeometry(QtCore.QRect(340, 20, 321, 411))
        self.fmLogistico.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fmLogistico.setFrameShadow(QtGui.QFrame.Raised)
        self.fmLogistico.setObjectName("fmLogistico")
        self.groupBox_7 = QtGui.QGroupBox(self.fmLogistico)
        self.groupBox_7.setEnabled(True)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 30, 271, 331))
        self.groupBox_7.setObjectName("groupBox_7")
        self.layoutWidget = QtGui.QWidget(self.groupBox_7)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 31, 222, 220))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_17.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEditPopLog = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditPopLog.setObjectName("lineEditPopLog")
        self.gridLayout_17.addWidget(self.lineEditPopLog, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_17, 0, 0, 1, 1)
        self.gridLayout_18 = QtGui.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_18.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEditTempoLog = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditTempoLog.setObjectName("lineEditTempoLog")
        self.gridLayout_18.addWidget(self.lineEditTempoLog, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem3, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem4, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_18, 1, 0, 1, 1)
        self.gridLayout_19 = QtGui.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.groupBox_8 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_20 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.lineEditCresc = QtGui.QLineEdit(self.groupBox_8)
        self.lineEditCresc.setObjectName("lineEditCresc")
        self.gridLayout_20.addWidget(self.lineEditCresc, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_21 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.lineEditCapSup = QtGui.QLineEdit(self.groupBox_9)
        self.lineEditCapSup.setObjectName("lineEditCapSup")
        self.gridLayout_21.addWidget(self.lineEditCapSup, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_9, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_19, 2, 0, 1, 1)

        self.retranslateUi(JanelaModelo)
        QtCore.QMetaObject.connectSlotsByName(JanelaModelo)

    def retranslateUi(self, JanelaModelo):
        JanelaModelo.setWindowTitle(QtGui.QApplication.translate("JanelaModelo", "Janela Modelo", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("JanelaModelo", "Escolha o Modelo", None, QtGui.QApplication.UnicodeUTF8))
        self.cbModelList.setItemText(0, QtGui.QApplication.translate("JanelaModelo", "Nenhum", None, QtGui.QApplication.UnicodeUTF8))
        self.cbModelList.setItemText(1, QtGui.QApplication.translate("JanelaModelo", "Modelo Exponencial Contínuo Determinístico", None, QtGui.QApplication.UnicodeUTF8))
        self.cbModelList.setItemText(2, QtGui.QApplication.translate("JanelaModelo", "Modelo Logístico Contínuo Determinístico", None, QtGui.QApplication.UnicodeUTF8))
        self.cbModelList.setItemText(3, QtGui.QApplication.translate("JanelaModelo", "Outros", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("JanelaModelo", "Modelo Exponencial Contínuo Determinístico", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("JanelaModelo", "População Inicial", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditPopExp.setText(QtGui.QApplication.translate("JanelaModelo", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("JanelaModelo", "Duração/Tempo", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditTempoExp.setText(QtGui.QApplication.translate("JanelaModelo", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("JanelaModelo", "Taxa de Natalidade", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditNatalidade.setText(QtGui.QApplication.translate("JanelaModelo", "0.9", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("JanelaModelo", "Taxa de Mortalidade", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditMortalidade.setText(QtGui.QApplication.translate("JanelaModelo", "0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.pbOk.setText(QtGui.QApplication.translate("JanelaModelo", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancel.setText(QtGui.QApplication.translate("JanelaModelo", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("JanelaModelo", "Modelo Logistico Contínuo Determinístico", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("JanelaModelo", "População Inicial", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditPopLog.setText(QtGui.QApplication.translate("JanelaModelo", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("JanelaModelo", "Duração/Tempo", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditTempoLog.setText(QtGui.QApplication.translate("JanelaModelo", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("JanelaModelo", "Taxa de Crescimento (r)", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditCresc.setText(QtGui.QApplication.translate("JanelaModelo", "0.9", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("JanelaModelo", "Capacidade de Suporte (K)", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditCapSup.setText(QtGui.QApplication.translate("JanelaModelo", "200", None, QtGui.QApplication.UnicodeUTF8))

